### ISSUE TITLE
Unable to load nifti files directly

### ISSUE THREAD

**Issue by seqasim** [Rolston-Lab/LeGUI#1]
Hi, 

I'm looking forward to using this nice tool. However, I don't have the DICOM files, but only the nifti files for my subjects. 

I followed the instructions for renaming those files and placing them in a directory called "Registered", and then selecting this directory in the GUI. 

However, I then hear MATLAB's error ping, the GUI remains blank, and the "Load Images" button is grayed out and cannot be pressed again. 

I am using MATLAB 2021b on MacOS Monterey 12.1. 

Thanks!

**Comment by tyler-davis** [comment]
It sounds like you are missing some MATLAB toolboxes. Make sure the following toolboxes are installed:

Image Processing, Parallel Computing, and Statistics and Machine Learning

**Comment by tyler-davis** [comment]
The plan is to have future LeGUI versions automatically check for this on startup instead of crashing without warning. Let me know how it goes!

**Comment by seqasim** [comment]
Hi Tyler,

Thanks for the reply! 

I checked, and I already have all 3 of these toolboxes installed. Are there any more niche toolbox dependencies that I might be missing? Perhaps I can just fully mimic your MATLAB install? 

Thanks!

**Comment by tyler-davis** [comment]
Are you running compiled or source code? If compiled, try running the source code. If it still crashes, let me know what errors are printed to the command window. This could be related to your MATLAB installation or the nifti files themselves. If you are comfortable sharing the files, I could do some troubleshooting as well.

Thanks!
Tyler

On Feb 12, 2022, at 6:56 AM, seqasim ***@***.***> wrote:

﻿

Hi Tyler,

Thanks for the reply!

I checked, and I already have all 3 of these toolboxes installed. Are there any more niche toolbox dependencies that I might be missing? Perhaps I can just fully mimic your MATLAB install?

Thanks!

**Comment by seqasim** [comment]
Hey,

Thanks for pointing out that there are compiled/source versions... I had somehow glossed over this and was stupidly trying to run the compiled code in MATLAB, not MATLAB Runtime. 

So, the source code in MATLAB worked perfectly, and then the compiled code in MATLAB Runtime worked perfectly. 

Thanks again for your help!
