### ISSUE TITLE
Co-register post-op CT to post-op MRI, then to pre-op MRI?

### ISSUE THREAD

**Issue by ErnestJohnston** [Rolston-Lab/LeGUI#7]
Hello,

Is there a way to co-register the post-operative CT first to the post-operative MRI and then to co-register that to the pre-operative MRI?

Thanks.

**Comment by tyler-davis** [comment]
If you want the CT and post-op MRI registered to the pre-op MRI, you can trick the software by renaming files in the Registered folder. First, run LeGUI normally with the CT and preMRI. This will coregister the CT to preMRI. Then, in the Registered folder, rename the MR.nii, CT.nii, MR_coreg.mat, and ACPCmm.mat by adding "2" at the end of each name and rerun LeGUI. The parseDICOMGUI window should appear, and you can now select the postMRI. Once you save this image (i.e. close the ACPCGUI window) a new MR.nii will appear in the Registered folder. Rename this file to CT.nii and change the previous MR2.nii and ACPCmm2.mat back to MR.nii and ACPCmm.mat. Once you close the parseDICOMGUI window, the CT.nii (which is actually postMRI) will be coregistered to the preMRI. You can visualize the result in LeGUI using the slider to fade in/out the postMRI relative to the preMRI. If you want to view the CT in LeGUI again, just rename CT.nii to something else and change CT2.nii back to CT.nii and reload the images. Hopefully this helps!

**Comment by ErnestJohnston** [comment]
Hi Tyler -- thanks for this suggestion. Based on your explanation, I can use LeGUI to register the CT-preMRI to the postMRI space, but it's not clear to me that doing so will account for brain shift when assigning electrode locations. Let me explain:

- To maximize the accuracy of electrode localization, I want to register CT-postMRI 
- To maximize the accuracy of atlas ROI assignment, I want to register postMRI-preMRI

I can do both of the above in LeGUI by running them separately, but connecting the two registrations is where I am confused (CT-postMRI and postMRI-preMRI). Using your method, how can the electrode locations in CT-postMRI space be transformed into preMRI space?

**Comment by tyler-davis** [comment]
The coregistration in LeGUI is linear/rigid, so it can’t account for things like brain shift. However, the registration to standard MNI space (atlas space) is nonlinear and might be able to account for the shift. If you run LeGUI on the CT/postMRI, the postMRI will be warped to MNI space and this will likely include the brain shift. How well does the atlas match up with the brain when you run the CT/postMRI combination? To check, set the overlay drop-down to “atlas” and move the slider bar at the bottom. If it reasonably accounts for the shift, this is probably the best you can do with LeGUI.

There is potentially a way of going from preMRI to postMRI using the transformation matrices iy_MR.nii in the registered folders, but this a bit more involved. Unfortunately, LeGUI doesn’t have the ability to perform a direct nonlinear registration of preMRI to postMRI. You can use a different package like FSL to perform this type of transformation if needed.


On Mar 26, 2023, at 8:05 AM, ErnestJohnston ***@***.***> wrote:

﻿

Hi Tyler -- thanks for this suggestion. Based on your explanation, I can use LeGUI to register the CT-preMRI to the postMRI space, but it's not clear to me that doing so will account for brain shift when assigning electrode locations. Let me explain:

  *   To maximize the accuracy of electrode localization, I want to register CT-postMRI
  *   To maximize the accuracy of atlas ROI assignment, I want to register postMRI-preMRI

I can do both of the above in LeGUI by running them separately, but connecting the two registrations is where I am confused (CT-postMRI and postMRI-preMRI). Using your method, how can the electrode locations in CT-postMRI space be transformed into preMRI space?

**Comment by ErnestJohnston** [comment]
Thank you for this explanation Tyler! It makes sense to me now -- much appreciated.
